receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

#  resource:
#    attributes:
#      - key: service.name
#        value: book-api
#        action: upsert
#      - key: service.version
#        value: "1.0.0"
#        action: upsert
#      - key: deployment.environment
#        value: docker
#        action: upsert

  memory_limiter:
    limit_mib: 128
    spike_limit_mib: 32
    check_interval: 5s

exporters:
  otlp:
    endpoint: jaeger:14250
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1

  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    format: json
    labels:
      attributes:
        service.name: "service_name"
        service.version: "service_version"

  logging:
    loglevel: info

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp, logging]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus, logging]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [loki, logging]

  extensions: []